/* Generated config file */

module.exports = {
  "label": "Af-Somali",
  "code": "so",
  "layout": {
    "style": "table",
    "indexes" : [
      [2,25,13,29,15,4,22,23],
      [24,5,3,9,8,21,14,16],
      [17,18,28,10,30],
      [0,6,11,19,26],
      [1,7,12,20,27]
    ]
  },
  "phonemes": [{
    "id": 0,
    "label": "a",
    "key": "a"
  }, {
    "id": 1,
    "label": "aa",
    "key": "aa"
  }, {
    "id": 2,
    "label": "b",
    "key": "b"
  }, {
    "id": 3,
    "label": "c",
    "key": "c"
  }, {
    "id": 4,
    "label": "d",
    "key": "d"
  }, {
    "id": 5,
    "label": "dh",
    "key": "dh"
  }, {
    "id": 6,
    "label": "e",
    "key": "e"
  }, {
    "id": 7,
    "label": "ee",
    "key": "ee"
  }, {
    "id": 8,
    "label": "f",
    "key": "f"
  }, {
    "id": 9,
    "label": "g",
    "key": "g"
  }, {
    "id": 10,
    "label": "h",
    "key": "h"
  }, {
    "id": 11,
    "label": "i",
    "key": "i"
  }, {
    "id": 12,
    "label": "ii",
    "key": "ii"
  }, {
    "id": 13,
    "label": "j",
    "key": "j"
  }, {
    "id": 14,
    "label": "k",
    "key": "k"
  }, {
    "id": 15,
    "label": "kh",
    "key": "kh"
  }, {
    "id": 16,
    "label": "l",
    "key": "l"
  }, {
    "id": 17,
    "label": "m",
    "key": "m"
  }, {
    "id": 18,
    "label": "n",
    "key": "n"
  }, {
    "id": 19,
    "label": "o",
    "key": "o"
  }, {
    "id": 20,
    "label": "oo",
    "key": "oo"
  }, {
    "id": 21,
    "label": "q",
    "key": "q"
  }, {
    "id": 22,
    "label": "r",
    "key": "r"
  }, {
    "id": 23,
    "label": "s",
    "key": "s"
  }, {
    "id": 24,
    "label": "sh",
    "key": "sh"
  }, {
    "id": 25,
    "label": "t",
    "key": "t"
  }, {
    "id": 26,
    "label": "u",
    "key": "u"
  }, {
    "id": 27,
    "label": "uu",
    "key": "uu"
  }, {
    "id": 28,
    "label": "w",
    "key": "w"
  }, {
    "id": 29,
    "label": "x",
    "key": "x"
  }, {
    "id": 30,
    "label": "y",
    "key": "y"
  }]
};