/* Generated config file */

module.exports = {
  "label": "Sidaamu Afoo",
  "code": "sd",
  "layout": {
    "style": "table",
    "indexes" : [
      [0,7,9,10,11,12,13],
      [14,16,17,18,19,21,22],
      [23,24,25,26,27,29,30],
      [31,32,33,34,35,36,37],
      [39,40,41,42,43,44],
      [8,15,20,28,38],
      [1,2,3,4,5,6]
    ]
  },
  "phonemes": [{
    "id": 0,
    "label": "'",
    "key": "'"
  }, {
    "id": 1,
    "label": "'l",
    "key": "'l"
  }, {
    "id": 2,
    "label": "'m",
    "key": "'m"
  }, {
    "id": 3,
    "label": "'n",
    "key": "'n"
  }, {
    "id": 4,
    "label": "'ny",
    "key": "'ny"
  }, {
    "id": 5,
    "label": "'r",
    "key": "'r"
  }, {
    "id": 6,
    "label": "'y",
    "key": "'y"
  }, {
    "id": 7,
    "label": "a",
    "key": "a"
  }, {
    "id": 8,
    "label": "aa",
    "key": "aa"
  }, {
    "id": 9,
    "label": "b",
    "key": "b"
  }, {
    "id": 10,
    "label": "c",
    "key": "c"
  }, {
    "id": 11,
    "label": "ch",
    "key": "ch"
  }, {
    "id": 12,
    "label": "d",
    "key": "d"
  }, {
    "id": 13,
    "label": "dh",
    "key": "dh"
  }, {
    "id": 14,
    "label": "e",
    "key": "e"
  }, {
    "id": 15,
    "label": "ee",
    "key": "ee"
  }, {
    "id": 16,
    "label": "f",
    "key": "f"
  }, {
    "id": 17,
    "label": "g",
    "key": "g"
  }, {
    "id": 18,
    "label": "h",
    "key": "h"
  }, {
    "id": 19,
    "label": "i",
    "key": "i"
  }, {
    "id": 20,
    "label": "ii",
    "key": "ii"
  }, {
    "id": 21,
    "label": "j",
    "key": "j"
  }, {
    "id": 22,
    "label": "k",
    "key": "k"
  }, {
    "id": 23,
    "label": "l",
    "key": "l"
  }, {
    "id": 24,
    "label": "m",
    "key": "m"
  }, {
    "id": 25,
    "label": "n",
    "key": "n"
  }, {
    "id": 26,
    "label": "ny",
    "key": "ny"
  }, {
    "id": 27,
    "label": "o",
    "key": "o"
  }, {
    "id": 28,
    "label": "oo",
    "key": "oo"
  }, {
    "id": 29,
    "label": "p",
    "key": "p"
  }, {
    "id": 30,
    "label": "ph",
    "key": "ph"
  }, {
    "id": 31,
    "label": "q",
    "key": "q"
  }, {
    "id": 32,
    "label": "r",
    "key": "r"
  }, {
    "id": 33,
    "label": "s",
    "key": "s"
  }, {
    "id": 34,
    "label": "sh",
    "key": "sh"
  }, {
    "id": 35,
    "label": "t",
    "key": "t"
  }, {
    "id": 36,
    "label": "ts",
    "key": "ts"
  }, {
    "id": 37,
    "label": "u",
    "key": "u"
  }, {
    "id": 38,
    "label": "uu",
    "key": "uu"
  }, {
    "id": 39,
    "label": "v",
    "key": "v"
  }, {
    "id": 40,
    "label": "w",
    "key": "w"
  }, {
    "id": 41,
    "label": "x",
    "key": "x"
  }, {
    "id": 42,
    "label": "y",
    "key": "y"
  }, {
    "id": 43,
    "label": "z",
    "key": "z"
  }, {
    "id": 44,
    "label": "zh",
    "key": "zh"
  }]
};