/* Generated config file */

module.exports = {
  "label": "Hadiyyisa",
  "code": "hy",
  "layout": {
    "style": "table",
    "indexes" : [
      [6,7,8,9,10,11],
      [12,13,14,15,16],
      [17,18,19,20,21,1],
      [22,2,23,3,24,25,26],
      [27,28,29,30,31,32,4],
      [33,34,35,36,37,38],
      [39,41,42,40,5,0]
    ]
  },
  "phonemes": [{
    "id": 0,
    "label": "'",
    "key": "'"
  }, {
    "id": 1,
    "label": "'l",
    "key": "'l"
  }, {
    "id": 2,
    "label": "'m",
    "key": "'m"
  }, {
    "id": 3,
    "label": "'n",
    "key": "'n"
  }, {
    "id": 4,
    "label": "'w",
    "key": "'w"
  }, {
    "id": 5,
    "label": "'y",
    "key": "'y"
  }, {
    "id": 6,
    "label": "a",
    "key": "a"
  }, {
    "id": 7,
    "label": "aa",
    "key": "aa"
  }, {
    "id": 8,
    "label": "b",
    "key": "b"
  }, {
    "id": 9,
    "label": "c",
    "key": "c"
  }, {
    "id": 10,
    "label": "ch",
    "key": "ch"
  }, {
    "id": 11,
    "label": "d",
    "key": "d"
  }, {
    "id": 12,
    "label": "e",
    "key": "e"
  }, {
    "id": 13,
    "label": "ee",
    "key": "ee"
  }, {
    "id": 14,
    "label": "f",
    "key": "f"
  }, {
    "id": 15,
    "label": "g",
    "key": "g"
  }, {
    "id": 16,
    "label": "h",
    "key": "h"
  }, {
    "id": 17,
    "label": "i",
    "key": "i"
  }, {
    "id": 18,
    "label": "ii",
    "key": "ii"
  }, {
    "id": 19,
    "label": "j",
    "key": "j"
  }, {
    "id": 20,
    "label": "k",
    "key": "k"
  }, {
    "id": 21,
    "label": "l",
    "key": "l"
  }, {
    "id": 22,
    "label": "m",
    "key": "m"
  }, {
    "id": 23,
    "label": "n",
    "key": "n"
  }, {
    "id": 24,
    "label": "ny",
    "key": "ny"
  }, {
    "id": 25,
    "label": "o",
    "key": "o"
  }, {
    "id": 26,
    "label": "oo",
    "key": "oo"
  }, {
    "id": 27,
    "label": "p",
    "key": "p"
  }, {
    "id": 28,
    "label": "ph",
    "key": "ph"
  }, {
    "id": 29,
    "label": "q",
    "key": "q"
  }, {
    "id": 30,
    "label": "r",
    "key": "r"
  }, {
    "id": 31,
    "label": "s",
    "key": "s"
  }, {
    "id": 32,
    "label": "sh",
    "key": "sh"
  }, {
    "id": 33,
    "label": "t",
    "key": "t"
  }, {
    "id": 34,
    "label": "ts",
    "key": "ts"
  }, {
    "id": 35,
    "label": "u",
    "key": "u"
  }, {
    "id": 36,
    "label": "uu",
    "key": "uu"
  }, {
    "id": 37,
    "label": "v",
    "key": "v"
  }, {
    "id": 38,
    "label": "w",
    "key": "w"
  }, {
    "id": 39,
    "label": "x",
    "key": "x"
  }, {
    "id": 40,
    "label": "y",
    "key": "y"
  }, {
    "id": 41,
    "label": "z",
    "key": "z"
  }, {
    "id": 42,
    "label": "zh",
    "key": "zh"
  }]
};