/* Generated config file */

module.exports = {
  "label": "Wolayttatto",
  "code": "wt",
  "layout": {
    "style": "table",
    "indexes" : [
      [2,57,17,20,3,44,28],
      [48,34,10,19,14,42,30],
      [50,22,51,35,21,26,4],
      [54,24,15,40,55,45,47],
      [1,6,52,25,36,59,9],
      [11,16,18,46,41,5,27],
      [29,39,7,0,33,56,58],
      [37,62,23,13,38,8,53],
      [60,12,43,31,32,49,61]
    ]
  },
  "phonemes": [{
    "id": 0,
    "label": "''",
    "key": "''"
  }, {
    "id": 1,
    "label": "'",
    "key": "'"
  }, {
    "id": 2,
    "label": "a",
    "key": "a"
  }, {
    "id": 3,
    "label": "aa",
    "key": "aa"
  }, {
    "id": 4,
    "label": "b",
    "key": "b"
  }, {
    "id": 5,
    "label": "bb",
    "key": "bb"
  }, {
    "id": 6,
    "label": "c",
    "key": "c"
  }, {
    "id": 7,
    "label": "cc",
    "key": "cc"
  }, {
    "id": 8,
    "label": "ch",
    "key": "ch"
  }, {
    "id": 9,
    "label": "chch",
    "key": "chch"
  }, {
    "id": 10,
    "label": "d",
    "key": "d"
  }, {
    "id": 11,
    "label": "dd",
    "key": "dd"
  }, {
    "id": 12,
    "label": "dh",
    "key": "dh"
  }, {
    "id": 13,
    "label": "dhdh",
    "key": "dhdh"
  }, {
    "id": 14,
    "label": "e",
    "key": "e"
  }, {
    "id": 15,
    "label": "ee",
    "key": "ee"
  }, {
    "id": 16,
    "label": "f",
    "key": "f"
  }, {
    "id": 17,
    "label": "g",
    "key": "g"
  }, {
    "id": 18,
    "label": "gg",
    "key": "gg"
  }, {
    "id": 19,
    "label": "h",
    "key": "h"
  }, {
    "id": 20,
    "label": "i",
    "key": "i"
  }, {
    "id": 21,
    "label": "ii",
    "key": "ii"
  }, {
    "id": 22,
    "label": "j",
    "key": "j"
  }, {
    "id": 23,
    "label": "jj",
    "key": "jj"
  }, {
    "id": 24,
    "label": "k",
    "key": "k"
  }, {
    "id": 25,
    "label": "kk",
    "key": "kk"
  }, {
    "id": 26,
    "label": "l",
    "key": "l"
  }, {
    "id": 27,
    "label": "ll",
    "key": "ll"
  }, {
    "id": 28,
    "label": "m",
    "key": "m"
  }, {
    "id": 29,
    "label": "mm",
    "key": "mm"
  }, {
    "id": 30,
    "label": "n",
    "key": "n"
  }, {
    "id": 31,
    "label": "nh",
    "key": "nh"
  }, {
    "id": 32,
    "label": "nhnh",
    "key": "nhnh"
  }, {
    "id": 33,
    "label": "nn",
    "key": "nn"
  }, {
    "id": 34,
    "label": "o",
    "key": "o"
  }, {
    "id": 35,
    "label": "oo",
    "key": "oo"
  }, {
    "id": 36,
    "label": "p",
    "key": "p"
  }, {
    "id": 37,
    "label": "ph",
    "key": "ph"
  }, {
    "id": 38,
    "label": "phph",
    "key": "phph"
  }, {
    "id": 39,
    "label": "pp",
    "key": "pp"
  }, {
    "id": 40,
    "label": "q",
    "key": "q"
  }, {
    "id": 41,
    "label": "qq",
    "key": "qq"
  }, {
    "id": 42,
    "label": "r",
    "key": "r"
  }, {
    "id": 43,
    "label": "rr",
    "key": "rr"
  }, {
    "id": 44,
    "label": "s",
    "key": "s"
  }, {
    "id": 45,
    "label": "sh",
    "key": "sh"
  }, {
    "id": 46,
    "label": "shsh",
    "key": "shsh"
  }, {
    "id": 47,
    "label": "ss",
    "key": "ss"
  }, {
    "id": 48,
    "label": "t",
    "key": "t"
  }, {
    "id": 49,
    "label": "ts",
    "key": "ts"
  }, {
    "id": 50,
    "label": "tt",
    "key": "tt"
  }, {
    "id": 51,
    "label": "u",
    "key": "u"
  }, {
    "id": 52,
    "label": "uu",
    "key": "uu"
  }, {
    "id": 53,
    "label": "v",
    "key": "v"
  }, {
    "id": 54,
    "label": "w",
    "key": "w"
  }, {
    "id": 55,
    "label": "x",
    "key": "x"
  }, {
    "id": 56,
    "label": "xx",
    "key": "xx"
  }, {
    "id": 57,
    "label": "y",
    "key": "y"
  }, {
    "id": 58,
    "label": "yy",
    "key": "yy"
  }, {
    "id": 59,
    "label": "z",
    "key": "z"
  }, {
    "id": 60,
    "label": "zh",
    "key": "zh"
  }, {
    "id": 61,
    "label": "zhzh",
    "key": "zhzh"
  }, {
    "id": 62,
    "label": "zz",
    "key": "zz"
  }]
};